FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src/ui/ /app/src/ui/
COPY final_pinn_model.pth .
COPY datasets/ /app/datasets/

EXPOSE 8501

CMD ["streamlit", "run", "src/ui/comparison.py", "--server.address=0.0.0.0"]