services:
  # The Scientific FastAPI Backend
  - type: web
    name: pinnflow-api
    runtime: docker
    dockerfilePath: ./Dockerfile.api
    plan: free
    healthCheckPath: /docs

  # The Streamlit Interactive UI
  - type: web
    name: pinnflow-ui
    runtime: docker
    dockerfilePath: ./Dockerfile.ui
    plan: starter # Upgraded to resolve the 1-free-service limit
    envVars:
      - key: API_URL
        value: http://pinnflow-api:8000/predict/field