services:
  # The Scientific FastAPI Backend
  - type: web
    name: pinnflow-api
    env: docker
    dockerfilePath: ./Dockerfile.api
    plan: free
    healthCheckPath: /docs

  # The Streamlit Interactive UI
  - type: web
    name: pinnflow-ui
    env: docker
    dockerfilePath: ./Dockerfile.ui
    plan: free
    envVars:
      - key: API_URL
        # This will securely route internal traffic from the UI to the API on Render
        value: http://pinnflow-api:8000/predict/field